[package]
name = "magic-args"
version.workspace = true
authors = [ "threadexio" ]
edition.workspace = true
description = '''
"Magic" declarative-style function arguments.
'''
documentation.workspace = true
readme = "README.md"
homepage.workspace = true
repository.workspace = true
license.workspace = true
keywords.workspace = true
categories.workspace = true

[package.metadata.docs.rs]
all-features = true
rustc-args = [ "--cfg", "docsrs" ]
rustdoc-args = [ "--cfg", "docsrs", "--html-in-header", "./src/docs-header.html" ]

[dependencies]
magic-args-derive = { version = "0.1.3", path = "../magic-args-derive", optional = true }

[features]
derive = ["dep:magic-args-derive"]

default = ["derive"]

[lints]
workspace = true
